1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
array_1 = np.loadtxt('/content/minutes_n_ingredients.csv',dtype='int32',delimiter=';',skiprows=1)
print(array_1[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('min: ',np.min(array_1[:,1:3], axis=0))
print('max: ',np.max(array_1[:,1:3], axis=0))
print('avarage: ',np.mean(array_1[:,1:3], axis=0))
print('med: ',np.median(array_1[:,1:3], axis=0))

min:  [0 1]
max:  [2147483647         39]
avarage:  [2.16010017e+04 9.05528000e+00]
med:  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
res = array_1[:,1:2]
print(np.quantile(res, 0.75, axis = 0)) # Вычисляем значение квантиля
q = np.quantile(array_1[:, 1], 0.75)
array_1[:, 1] = np.clip(array_1[:, 1], a_min=0, a_max=q) # Ограничеваем элементы массива снизу нулем, сверху, квантилем
print(array_1[:30]) 

[65.]
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]
 [152828     40      7]
 [ 33941     18      9]
 [446597     15      5]
 [366174      7      9]
 [ 74205     20      7]
 [504666     65     20]
 [ 81006     12      7]
 [280968     65     11]
 [204134      5      3]
 [ 18593     35      7]
 [ 25623      6      4]
 [ 65559     24     14]
 [ 99836     65      7]
 [ 87775     65     13]
 [425704     40     12]
 [101799     10      8]
 [106325     65     11]
 [ 99283     65      6]
 [179504     65     11]
 [276123     60      7]
 [498382     65     18]
 [197140     40      6]
 [484223     18      4]
 [385472     65      9]
 [ 63150     65      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
res = array_1[:,1:2]
np.place(res, res==0,[1])
print(res[411])
print(res)

[1]
[[ 60]
 [ 25]
 [ 10]
 ...
 [ 65]
 [  5]
 [140]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
# print(np.unique(array_1[:, 1:3]))
print(len(np.unique(array_1[:,1:3])))

655


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
uniq, count = np.unique(array_1[:,2], return_counts=True) # аргумент return_counts возвращает количество раз, сколько данный элемент встретился в массиве
print('Количество уникальных ингридиентов:',len(uniq))
print(dict(zip(count, uniq)))

Количество уникальных ингридиентов: 37
{13: 1, 926: 2, 2895: 3, 5515: 4, 7913: 5, 9376: 6, 10628: 7, 10951: 8, 10585: 9, 9591: 10, 8297: 11, 6605: 12, 4997: 13, 3663: 14, 2595: 15, 1767: 16, 1246: 17, 790: 18, 573: 19, 376: 20, 217: 21, 161: 22, 105: 23, 69: 24, 50: 25, 28: 26, 16: 28, 12: 30, 3: 35, 1: 39, 2: 33}


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.


In [ ]:
res = array_1[array_1[:,2]<=5]
print(res)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
sr_ingr = np.max(array_1[:,2]//array_1[:,1])
print(sr_ingr)

24


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
print(np.mean(array_1[np.argsort(array_1[:,1])][-100:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
k = 10
index = np.random.choice(array_1.shape[0],k,replace=False) # параметр replace дает выбрать только уникальные элементы
print(array_1[index])

[[ 68166     20      9]
 [334969     50     13]
 [269911     60      4]
 [ 16744      1      5]
 [344260     50     13]
 [ 86577     65      6]
 [  9817     65      7]
 [119153     65      8]
 [146514     10      8]
 [ 29750     65     17]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
print(f'{array_1[array_1[:,2] < np.mean(array_1[:,2])].shape[0]/array_1.shape[0]*100} %')

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
easy_hard = np.c_[array_1, (array_1[:,1]<20) & (array_1[:,2]<5)]
print(easy_hard)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
easy_hard = np.c_[array_1,(array_1[:,1]<20) & (array_1[:,2]<5)]
easy = easy_hard[easy_hard[:,3] == 1].shape[0]
hard = easy_hard.shape[0]
print(f'{easy*100/hard} %')

5.093 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short = array_1[array_1[:,1]<10]
medium = array_1[(array_1[:,1]>=10) & (array_1[:,1]<20)]
lng = array_1[array_1[:,1]>=20]
d_f = np.min([short.shape[0], medium.shape[0], lng.shape[0]])
res = np.array([short[:d_f], medium[:d_f], lng[:d_f]])
print(res.shape)
print(res)

(3, 7588, 3)
[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
